# -*- coding: utf-8 -*-
"""StephenP_HeatMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11sAh2h52qPTKiYZ_RUD3uLU694dtdT4O
"""

# library
import seaborn as sns
import pandas as pd
import numpy as np

# Create a dataframe
df = pd.DataFrame(columns=['risk','likelihood','impact','score'])

# identify list of uncertainties
df['risk'] = ['users', 'team', 'budget', 'security']

# estimate likelihood of happening [0,1]
df['likelihood'] = [0.2, 0.3, 0.1, 0.5]

# assess severity of impact if uncertainty happens
df['impact'] = [1,2,7,10]

# calculate scores 
df['score'] = df['impact']*df['likelihood']

# create heatmap
scoresPivot = df.pivot('impact', 'likelihood', 'score')
print(scoresPivot)

labelsPivot = df.pivot('impact', 'likelihood', 'risk')
print(labelsPivot)


# simple heatmap
p1 = sns.heatmap(scoresPivot, cmap="RdYlGn_r", annot=labelsPivot, fmt='')