# -*- coding: utf-8 -*-
"""StephenP_ParetoChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hgIJlwb-NHJQPHYs1eUv0G9pGZ0zOBb
"""

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

# upload HelpDesk.csv to Drive
df = pd.read_csv("/content/drive/MyDrive/IT262 - IT Project Management/StephenP_ParetoChart/HelpDesk.csv")
print(df)

# set this column as index - to use as plot labels
df.index = df['reason']

# descending sort
df = df.sort_values(by='frequency', ascending=False)

# cumulative percentage column is created using cumsum function
df['cumuluativePercentage'] = df['frequency'].cumsum()/df['frequency'].sum()*100

# make sure only 2 decimal places are shown
df['cumuluativePercentage'] = df['cumuluativePercentage'].apply(lambda x: round(x,2))

print(df)

fig, ax = plt.subplots()
ax.bar(df.index, df['frequency'], color="C0")

# show labels diagonally
ax.set_xticklabels( df['reason'], rotation=45 )

# ax2 and ax1 will be shown at the same time with twinx
ax2 = ax.twinx()

ax2.plot(df.index, df['cumuluativePercentage'], color="C1", marker="D", ms=7)
ax2.yaxis.set_major_formatter(PercentFormatter())

ax.tick_params(axis="y", colors="C0")
ax2.tick_params(axis="y", colors="C1")

plt.show()