# -*- coding: utf-8 -*-
"""StephenP_CB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WTYbLtKU-he5SXRWkVfz6C3Rlguj6aJ-
"""

import pandas as pd
import math

dataT = pd.read_csv("/content/drive/MyDrive/262-CBA.csv")
print(dataT)

discountRate = 0.05

#calculate compound discount over time
#initialize a list of 4 elements, one for each year (0 to 3)

discountFactor = [0,0,0,0]

for year in dataT['years']:
  discountFactor[year] = 1/math.pow(1+discountRate, year)

dataT['discountFactor'] = [round(num,2) for num in discountFactor]
print(dataT)

#calculate net benefit/cost for each year
#sum of all benefits and costs for each year : op cost + dev cost + benefit

#initialize a list of 4 items
NetBC = [0,0,0,0]

for year in dataT['years']:
  NetBC[year] = dataT['developmentCost'][year] + dataT['operationalCost'][year] + dataT['valueOfBenefits'][year]

dataT['NetBC'] = NetBC
print(dataT)

#calculate the present value of the net b/c for each year (NPV)

#initialize a list of 4 items: one for each year
NPV = [0,0,0,0]

for year in dataT['years']:
  NPV[year] = dataT['NetBC'][year] * dataT['discountFactor'][year]

dataT['NPV'] = [round(num, 2) for num in NPV]
print(dataT)
